name: push images

on:
  push:

jobs:
  pull-container:
    name: pull and push container
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: cache venv
      id: venv
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-${{ hashFiles('requirements*') }}
        path: |
          ./venv

    - run: make venv
    - run: make pull_and_push
